[package]
name = "basscript-app"
version = "0.1.51"
edition = "2024"

[features]
default = []
dev-dynamic = ["bevy/dynamic_linking"]

[dependencies]
bevy = { path = "../../Hamerons_bevy", features = ["bmp", "http", "https", "jpeg", "webp"] }
basscript-ui = { path = "../ui" }
basscript-core = { path = "../core" }
