[package]
name = "basscript-app"
version = "0.1.19"
edition = "2024"

[features]
default = []
dev-dynamic = ["bevy/dynamic_linking"]

[dependencies]
bevy = { version = "0.18", features = ["bmp", "http", "https", "jpeg", "webp"] }
basscript-ui = { path = "../ui" }
basscript-core = { path = "../core" }
