[package]
name = "basscript-app"
version = "0.1.51"
edition = "2024"

[features]
default = []
dev-dynamic = ["bevy/dynamic_linking"]

[dependencies]
bevy.workspace = true
basscript-ui = { path = "../ui" }
basscript-core = { path = "../core" }

[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { version = "29", default-features = false, features = ["gles"] }
