# BasScript settings
# true: processed pane renders dialogue double spaces as new lines
dialogue_double_space_newline = true
# true: processed pane renders non-dialogue double spaces as new lines
non_dialogue_double_space_newline = false
# processed page margins in typographic points
page_margin_left = 66
page_margin_right = 66
page_margin_top = 120
page_margin_bottom = 0
