# BasScript settings
# true: processed pane renders dialogue double spaces as new lines
dialogue_double_space_newline = true
# true: processed pane renders non-dialogue double spaces as new lines
non_dialogue_double_space_newline = true
# processed page margins in typographic points
page_margin_left = 98
page_margin_right = 74
page_margin_top = 104
page_margin_bottom = 64
