[package]
name = "basscript-ui"
version = "0.1.35"
edition = "2024"

[dependencies]
bevy = { version = "0.18", features = ["bmp", "http", "https", "jpeg", "webp"] }
basscript-core = { path = "../core" }
ron = "0.12"
rfd = "0.15"
resvg = "0.45"
serde = { version = "1", features = ["derive"] }
winit = "0.30"

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
window-vibrancy = "0.7.1"

[target.'cfg(windows)'.dependencies]
arboard = { version = "3.6.1", default-features = false }
windows-sys = { version = "=0.61.2", features = ["Win32_Graphics_Gdi"] }

[target.'cfg(target_os = "linux")'.dependencies]
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control"] }
